version: 2

project_name: nanostore

builds:
  # Shared library for FFI bindings
  - id: nanostore-lib
    main: ./examples/c-bindings
    binary: libnanostore
    buildmode: c-shared
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=1
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    hooks:
      post:
        # Rename Windows DLL
        - cmd: sh -c 'if [ "{{ .Os }}" = "windows" ]; then mv {{ .Path }} {{ dir .Path }}/nanostore.dll; fi'

# before hooks removed - no CLI to generate completions for

archives:
  # Archive for shared libraries
  - id: nanostore-lib-archive
    ids: [nanostore-lib]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "nanostore-lib_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: "examples/c-bindings/libnanostore.h"
        dst: "include/nanostore.h"
        info:
          mode: 0644

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

# No brew or package distributions for library-only release

env:
  - PKG_NAME={{ .Env.PKG_NAME }}
