version: 2

project_name: nanostore

builds:
  - id: nanostore
    main: ./cmd
    binary: nanostore
    ldflags:

      - -s -w -X github.com/arthur-debert/nanostore/internal/version.Version={{.Version}} -X github.com/arthur-debert/nanostore/internal/version.Commit={{.Commit}} -X github.com/arthur-debert/nanostore/internal/version.Date={{.Date}}

    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

before:
  hooks:
    # Generate completions and man pages before archiving
    - ./scripts/gen-completion
    - ./scripts/gen-manpage

archives:
  - id: nanostore-archive
    ids: [nanostore]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "nanostore-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: "README.md"
        info:
          mode: 0644
      - src: "LICENSE"
        info:
          mode: 0644
      - src: "completions/*"
        dst: "completions"
        info:
          mode: 0644
      - src: "man/man1/*"
        dst: "man/man1"
        info:
          mode: 0644

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

brews:
  - ids: [nanostore-archive]
    name: nanostore
    repository:
      owner: arthur-debert
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    # Fixed: Always use Formula directory (the debug conditional was causing issues)
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/arthur-debert/nanostore"
    description: "Description of your CLI tool"
    license: "MIT"
    test: |
      system "#{bin}/nanostore --help"
    install: |
      bin.install "nanostore"
      
      # Install shell completions
      bash_completion.install "completions/nanostore.bash" if File.exist?("completions/nanostore.bash")
      zsh_completion.install "completions/_nanostore" if File.exist?("completions/_nanostore")
      fish_completion.install "completions/nanostore.fish" if File.exist?("completions/nanostore.fish")
      
      # Install man page
      man1.install "man/man1/nanostore.1.gz" if File.exist?("man/man1/nanostore.1.gz")

# nFPM packages (deb, rpm, etc.)
# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: nanostore
    builds: [nanostore]
    formats: [deb, rpm, apk]
    package_name: nanostore
    file_name_template: "nanostore_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: "https://github.com/arthur-debert/nanostore"
    maintainer: "Arthur Debert <arthur@debert.xyz>"
    description: "Description of your CLI tool"
    license: "MIT"
    section: utils
    priority: optional
    contents:
      # Man page
      - src: man/man1/nanostore.1.gz
        dst: /usr/share/man/man1/nanostore.1.gz
        file_info:
          mode: 0644
      # Bash completion
      - src: completions/nanostore.bash
        dst: /usr/share/bash-completion/completions/nanostore
        file_info:
          mode: 0644
      # Zsh completion
      - src: completions/_nanostore
        dst: /usr/share/zsh/site-functions/_nanostore
        file_info:
          mode: 0644
      # Fish completion
      - src: completions/nanostore.fish
        dst: /usr/share/fish/vendor_completions.d/nanostore.fish
        file_info:
          mode: 0644

env:
  - PKG_NAME={{ .Env.PKG_NAME }}
