-- Resolves UUID for a flat (single-level) user-facing ID
-- This handles cases like "1", "c2", "hp3" etc.
-- Uses ROW_NUMBER() with appropriate partitioning to find the document at the specified position
--
-- Template structure (dynamically built based on configuration):
-- WITH numbered_docs AS (
--   SELECT uuid, ROW_NUMBER() OVER (PARTITION BY <dimension_columns> ORDER BY created_at) as row_num
--   FROM documents 
--   WHERE <dimension_filters>
-- )
-- SELECT uuid FROM numbered_docs WHERE row_num = ?